#!/usr/bin/env bash
# JellymountPlus — Build script (see build.ps1 for details)
#
# Produces three dist artifacts:
#   dist/jellymountplus.css        THE THEME — pure CSS, paste into
#                                  Dashboard → Branding → Custom CSS.
#   dist/jellymountplus-full.css   theme + styles for the optional JS extras
#                                  (hero, hover preview). Only needed if you
#                                  install the extras/ loader.
#   dist/jellymountplus-extras.js  bundled optional JS extras.
set -euo pipefail
cd "$(dirname "$0")"

# Pure theme: styles Jellyfin's own DOM only. hero.css and hover-preview.css
# are excluded — they style elements the optional JS layer injects.
css_theme=(variables.css base.css navigation.css rails.css cards.css details.css search.css livetv.css player.css responsive.css accessibility.css)
css_extras=(hero.css hover-preview.css)
js_order=(jellymountplus.js navigation.js hero.js rails.js hover-preview.js details.js)

header="/* JellymountPlus bundle — generated by build.sh. Do not edit; edit styles/ and extras/scripts/ instead. */"

{
  echo "$header"
  for f in "${css_theme[@]}"; do
    echo "/* ===== styles/$f ===== */"; cat "styles/$f"
  done
} > dist/jellymountplus.css

{
  echo "$header"
  for f in "${css_theme[@]}" "${css_extras[@]}"; do
    echo "/* ===== styles/$f ===== */"; cat "styles/$f"
  done
} > dist/jellymountplus-full.css

{
  echo "$header"
  for f in "${js_order[@]}"; do
    echo "/* ===== extras/scripts/$f ===== */"; cat "extras/scripts/$f"
  done
} > dist/jellymountplus-extras.js

echo "Wrote dist/jellymountplus.css (theme), dist/jellymountplus-full.css (+extras styles), dist/jellymountplus-extras.js"
