# JellymountPlus — Build script
# Produces three dist artifacts:
#   dist/jellymountplus.css        THE THEME — pure CSS, paste into
#                                  Dashboard → Branding → Custom CSS.
#   dist/jellymountplus-full.css   theme + styles for the optional JS extras
#                                  (hero, hover preview). Only needed if you
#                                  install the extras/ loader.
#   dist/jellymountplus-extras.js  bundled optional JS extras.
#
# Usage:  powershell -File build.ps1        (from the JellymountPlus dir)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

# Pure theme: styles Jellyfin's own DOM only. hero.css and hover-preview.css
# are excluded — they style elements the optional JS layer injects.
$cssTheme = @(
    'variables.css', 'base.css', 'mui.css', 'navigation.css', 'rails.css',
    'cards.css', 'details.css', 'search.css',
    'livetv.css', 'player.css', 'responsive.css', 'accessibility.css'
)
$cssExtras = @('hero.css', 'hover-preview.css')

$jsOrder = @(
    'jellymountplus.js', 'navigation.js', 'hero.js', 'rails.js',
    'hover-preview.js', 'details.js'
)

$header = "/* JellymountPlus bundle — generated by build.ps1. Do not edit; edit styles/ and extras/scripts/ instead. */`n"

$theme = $header
foreach ($f in $cssTheme) {
    $theme += "`n/* ===== styles/$f ===== */`n" + (Get-Content (Join-Path $root "styles/$f") -Raw)
}
Set-Content (Join-Path $root 'dist/jellymountplus.css') $theme -Encoding utf8

$full = $header
foreach ($f in ($cssTheme + $cssExtras)) {
    $full += "`n/* ===== styles/$f ===== */`n" + (Get-Content (Join-Path $root "styles/$f") -Raw)
}
Set-Content (Join-Path $root 'dist/jellymountplus-full.css') $full -Encoding utf8

$js = $header
foreach ($f in $jsOrder) {
    $js += "`n/* ===== extras/scripts/$f ===== */`n" + (Get-Content (Join-Path $root "extras/scripts/$f") -Raw)
}
Set-Content (Join-Path $root 'dist/jellymountplus-extras.js') $js -Encoding utf8

Write-Host "Wrote dist/jellymountplus.css (theme), dist/jellymountplus-full.css (+extras styles), dist/jellymountplus-extras.js"
